& { $BinaryFormatter = New-Object -TypeName System.Runtime.Serialization.Formatters.Binary.BinaryFormatter
 @{ 
'FullPath.Name' = 'FullPath'
'btnRmvMon.Name' = 'btnRmvMon'
'Button1.Name' = 'Button1'
'btnStop.Name' = 'btnStop'
'TabPage1.Name' = 'TabPage1'
'txtMon.Name' = 'txtMon'
'ChangeType.Name' = 'ChangeType'
'FolderBrowserDialog1.Name' = 'FolderBrowserDialog1'
'btnStart.Name' = 'btnStart'
'btnAddMon.Name' = 'btnAddMon'
'lblWeb.Name' = 'lblWeb'
'TabPage2.Name' = 'TabPage2'
'Date.Name' = 'Date'
'tab.Name' = 'tab'
'tabConf.Name' = 'tabConf'
'txtWeb.Name' = 'txtWeb'
'DataGridView1.Name' = 'DataGridView1'
'txtRoot.Name' = 'txtRoot'
'btnAddWeb.Name' = 'btnAddWeb'
'tabDash.Name' = 'tabDash'
'btnRmvWeb.Name' = 'btnRmvWeb'
'lblRoot.Name' = 'lblRoot'
'lstMonitor.Name' = 'lstMonitor'
'lblStatus.Name' = 'lblStatus'
'lstWeb.Name' = 'lstWeb'
'$this.Name' = 'Form1'
'FolderBrowserDialog1.TrayLocation' = New-Object -TypeName System.Drawing.Point -ArgumentList @(169, 17)
'TextBox1.Name' = 'TextBox1'
'lblMonitor.Name' = 'lblMonitor'
'TabControl1.Name' = 'TabControl1'
}
}
